module.exports = [
  {
    id: "12abc",
    date: "2023-10-12",
    sourceTitle: "test",
    sourceDescription: "test description",
    sourceFrom: "me",
    amount: 10000,
    sourceCategory: 0,
    period: 0,
    misc: {},
  },
  {
    id: "asd0asdff",
    date: "2023-10-12",
    sourceTitle: "test2",
    sourceDescription: "test description",
    sourceFrom: "me",
    amount: 20,
    sourceCategory: 0,
    period: 0,
    misc: {},
  },
  {
    id: "37132sfaaa",
    date: "2023-10-13",
    sourceTitle: "test3",
    sourceDescription: "test description",
    sourceFrom: "me",
    amount: 30,
    sourceCategory: 0,
    period: 0,
    misc: {},
  }
]