module.exports = [
    {
      id: "1234",
      date: "2023-10-10",
      sourceTitle: "test",
      sourceDescription: "test description",
      sourceFrom: "me",
      amount: 1000,
      sourceCategory: 0,
      period: 0,
      misc: {},
    },
    {
      id: "asdf",
      date: "2023-10-12",
      sourceTitle: "test2",
      sourceDescription: "test description",
      sourceFrom: "me",
      amount: 20,
      sourceCategory: 0,
      period: 0,
      misc: {},
    },
    {
      id: "37132sf",
      date: "2023-10-13",
      sourceTitle: "test3",
      sourceDescription: "test description",
      sourceFrom: "me",
      amount: 30,
      sourceCategory: 0,
      period: 0,
      misc: {},
    }
]